---

- name: Check whether docker is already installed in {{ ansible_distribution }}
  command: "docker version"
  failed_when: false
  changed_when: false
  register: version_check_result

- name: Set is_installed fact in {{ ansible_distribution }}
  set_fact:
    is_installed: "{{ version_check_result.rc == 0 }}"

- name: Include {{ ansible_os_family }}-{{ docker_install_type }}.yml in {{ ansible_distribution }}
  include: "{{ ansible_os_family }}-{{ docker_install_type }}.yml"
  when: not is_installed