---
# tasks file for docker

- name: Include linux.yml in {{ ansible_distribution }} by {{ docker_install_type }} install
  include: linux.yml
  when: ansible_os_family!="Windows"

- name: Include window.yml in {{ ansible_distribution }} by {{ docker_install_type }} install
  include: window.yml
  when: ansible_os_family=="Windows"