---

- name: Install required packages for docker in {{ ansible_distribution }}
  yum: name={{ item }} state=present
  with_items:
    - yum-utils 
    - device-mapper-persistent-data 
    - lvm2

- name: Set up the stable repository in {{ ansible_distribution }}
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker in {{ ansible_distribution }}
  yum: name=docker-ce state=present

- name: Make sure a service is running in {{ ansible_distribution }}
  systemd: name=docker state=started