---

- name: Check whether docker is already installed for linux
  command: "docker version"
  failed_when: false
  changed_when: false
  register: version_check_result

- set_fact:
    is_installed: "{{ version_check_result.rc == 0 }}"

- block:

  - name: Install required packages for docker
    yum: name={{ item }} state=present
    with_items:
      - yum-utils 
      - device-mapper-persistent-data 
      - lvm2

  - name: Set up the stable repository
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install docker-ce
    yum: name=docker-ce state=present

  - name: Make sure a service is running
    systemd: name=docker state=started

  when: not is_installed


