---

- name: Check whether docker is already installed for window
  win_command: "docker"
  failed_when: false
  changed_when: false
  register: version_check_result

- set_fact:
    is_installed: "{{ version_check_result.rc == 0 }}"

- block:
    
    - set_fact:
        dir_info: "{{ docker_dir[ansible_os_family] }}"
        pkg_info: "{{ docker_packages[ansible_os_family] }}"

    - name: Check and create temp directory for window
      win_file: path={{ item }} state=directory
      with_items:
        - "{{ dir_info.tmp }}"

    - name: Download docker install package for window
      win_get_url: url={{ pkg_info.url }} dest={{ dir_info.tmp }}//{{ pkg_info.file }}

    - name: Install docker
      win_chocolatey: name=docker source={{ dir_info.tmp }} state=present

    - name: Remove docker install package
      win_file: path={{ dir_info.tmp }}//{{ pkg_info.file }} state=absent

  when: not is_installed

